services:
  # PostgreSQL Database
  - type: pserv
    name: financial-risk-db
    plan: free
    databaseName: financial_risk_db
    user: financial_user
    region: frankfurt
    
  # Backend API (Docker)
  - type: web
    name: financial-risk-api
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: financial-risk-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PORT
        value: "10000"
    
  # Frontend
  - type: web
    name: financial-risk-frontend
    env: static
    plan: free
    region: frankfurt
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://financial-risk-api.onrender.com