# Render Blueprint for Financial Risk Management Platform
services:
  # PostgreSQL Database
  - type: pserv
    name: financial-risk-db
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile.db
    
  # Backend API
  - type: web
    name: financial-risk-api
    env: python
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      alembic upgrade head
      python create_sample_data.py
    startCommand: |
      cd backend
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: financial-risk-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: '["https://financial-risk-frontend.onrender.com"]'
    
  # Frontend
  - type: web
    name: financial-risk-frontend
    env: static
    plan: free
    buildCommand: |
      npm install
      npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://financial-risk-api.onrender.com