version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: financial_risk_db
      POSTGRES_USER: financial_user
      POSTGRES_PASSWORD: financial_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U financial_user -d financial_risk_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://financial_user:financial_password@db:5432/financial_risk_db
      SECRET_KEY: your-super-secret-key-for-docker
      DEBUG: "True"
      PORT: 8000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "alembic upgrade head &&
             python create_sample_data.py &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data: