services:
  # PostgreSQL Database
  - type: pserv
    name: financial-risk-db
    plan: free
    databaseName: financial_risk_db
    user: financial_user
    region: frankfurt
    
  # Backend API
  - type: web
    name: financial-risk-api
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: financial-risk-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
    
  # Frontend
  - type: web
    name: financial-risk-frontend
    env: static
    plan: free
    region: frankfurt
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://financial-risk-api.onrender.com